### ISSUE TITLE
Facebook links will not generate image.

### ISSUE THREAD

**Issue by kodo-yousif** [hezhamen/awesome-kurds#18]
as the other project says you can add Facebook links also.
but if you add facebook link ther will be no image of you you will get just a placeholder image.

facebook images are hard to get from account Links and ther are ways to do it.
one way that i use is get them or more informations using **Web Scrapper**s
as example: [i used puppeter here](https://github.com/kodo-yousif/fb-image-scraping)

**Comment by rojvv** [comment]
Do you want to run puppeteer with the client's browser? 😂

**Comment by mhmd-azeez** [comment]
I was thinking of using something like cloudflare workers to fetch the images. But puppeteer is too heavy for them because they only have 10 ms per request. Unfortunately I could not get a way to get Facebook to send me the open graph tags (because they contain the profile image)

**Comment by kodo-yousif** [comment]
> 

i didn't say to run it on client it will need a server, you can make it a seperate project , it was just a recommendation. 😑
