### ISSUE TITLE
[feature]: add dropdown filter

### ISSUE THREAD

**Issue by RawandDev** [hezhamen/awesome-kurds#2]
I will add a dropdown to filter by tags since the current UI can get messier if people keep on adding tags.

**Comment by mhmd-azeez** [comment]
@hezhamen what do you think? Maybe we can use a tag input instead. Something like
https://www.npmjs.com/package/react-tag-input

**Comment by hezhamen** [comment]
The whole point was for user's to see what tags are available, so I think Rawand's solution is good. We need a dropdown tag filter.

**Comment by AramRafeq** [comment]
@mhmd-azeez ant design have a tag input it is a search component

**Comment by mhmd-azeez** [comment]
@AramRafeq can you paste the link to its documentation here?

**Comment by AramRafeq** [comment]
@mhmd-azeez  @hezhamen  search for tags mode 
https://ant.design/components/select/

**Comment by hezhamen** [comment]
I think using an input group would be a good solution, adding search and select together.

**Comment by RawandDev** [comment]
Here is my progress so far 👀

https://gyazo.com/c761d5d58c4d96ca504870728aff6ecc

**Comment by RawandDev** [comment]
and I already see that you are using css styles instead of ant design styles and layouts

**Comment by mhmd-azeez** [comment]
@RawandDev well done, looks great. But maybe we should go with [this](https://ant.design/components/select/) instead of a drop down? Because you can all of the options and you can select multiple tags. 
![image](https://user-images.githubusercontent.com/16880059/147393469-2bf29b4b-fab2-42df-823b-cee62919da6f.png)

@hezhamen what do you think? this or an input group? you decide.

**Comment by hezhamen** [comment]
I think a custom selection would be beneficial in the future for clients to select people that they want to hire. However, it would complicate the code a bit right now.

**Comment by RawandDev** [comment]
I tried this with an npm package before but it seemed to be hard to do. For example, I wanted to select both React and .NET but I couldn't get the users including these tags. I could only get one of them. Not sure if it is simpler with ant design or not but it looks much better imho.

**Comment by mhmd-azeez** [comment]
@RawandDev start a PR so that @hezhamen can collaborate with you and maybe you can fix the problems together

**Comment by RawandDev** [comment]
@hezhamen @mhmd-azeez please remove the log in the `index.js` since it might cause deployment issues. closes #3
