### ISSUE TITLE
Add a "contributor" badge to people who are working on the repo

### ISSUE THREAD

**Issue by hezhamen** [hezhamen/awesome-kurds#21]
Use <Badge.Ribbon /> from antd.
Maybe use a * on the readme file to indicate whether person is a contributor.

**Comment by RawandDev** [comment]
Are you working on this? I think we can't work on this because it requires token to get contributors list from a repo.

**Comment by hezhamen** [comment]
We're updating UI so we're not currently working on it.

**Comment by RawandDev** [comment]
Sounds good.
