### ISSUE TITLE
[question] why shuffling the bubbles on search

### ISSUE THREAD

**Issue by RawandDev** [hezhamen/awesome-kurds#22]
I wanted to know why would you shuffle the bubbles when the user searches? Wouldn't it be better to have fixed cards?
Note: after the changes, the bubbles are fixed and not changing even if you refresh.

Before the change:
https://gyazo.com/8612eecd174167e608801fe115245c4b

After the change:
https://gyazo.com/61df8c430d854f75ae3bd982b3c6d7a4

**Comment by AramRafeq** [comment]
Send a PR
