### ISSUE TITLE
[bug] not clickable links

### ISSUE THREAD

**Issue by RawandDev** [hezhamen/awesome-kurds#31]
You can't click on the link because of its z-index. Wanted to mention that the green background ruins the ui tbh.

https://gyazo.com/acc207679e57ad2b7cbfab61f5a3a2ca

**Comment by mhmd-azeez** [comment]
Looks a bit disgusting hahaha

**Comment by RawandDev** [comment]
Yeah, just a bit 🤔😂

**Comment by hezhamen** [comment]
Reverted the changes to fix this bug, I'll use the Green BG in the future when I have the complete header redesigned. 😂😂
