### ISSUE TITLE
The list gets stale if this repo is not deployed regularly

### ISSUE THREAD

**Issue by mhmd-azeez** [hezhamen/awesome-kurds#32]
I am not sure why we need server side rendering. We can fetch the list from the client side like before because now the list gets outdated if this repo is not deployed regularly.

Related: #27 and #28

**Comment by rojvv** [comment]
Is this still?

**Comment by mhmd-azeez** [comment]
@roj1512 sorry, what do you mean?

**Comment by rojvv** [comment]
ئەڵێم هێشتا ماوە؟

**Comment by mhmd-azeez** [comment]
@roj1512 yeah

**Comment by mhmd-azeez** [comment]
I don't think so, I will close it
