### ISSUE TITLE
Theme toggle issue 

### ISSUE THREAD

**Issue by AramRafeq** [hezhamen/awesome-kurds#34]
using double click on the document is not a good way of toggling the theme to dark mode or light mode as by accident i taped on the dropdowns twice and the theme toggled 
![image](https://user-images.githubusercontent.com/6641251/147774555-f660b0f7-f9b2-4ceb-875b-9e55a506a541.png)
if you change this feature to a floating button or a toggle button would be better

**Comment by rojvv** [comment]
I'm not kidding, but does your browser require you to double click to open the select menu?

**Comment by rojvv** [comment]
The actual goal of the double click is to make the dark mode switch a surprise, as inspired from [1.1.1.1](https://1.1.1.1). :)

**Comment by AramRafeq** [comment]
@roj1512  there is no need for sarcasm it happened and will happen

**Comment by rojvv** [comment]
@AramRafeq sure, turning that off.
