### ISSUE TITLE
[feature] use ant design rather than css

### ISSUE THREAD

**Issue by RawandDev** [hezhamen/awesome-kurds#4]
Not sure but I think it might be better to use ant design as much as you for styling and layout.
If it is fine I can try implementing it tomorrow but I barely have used ant design : )

**Comment by hezhamen** [comment]
I personally enjoy using Vanilla CSS more, but you can transfer them to antd. We'd be happy to merge your PRs.

**Comment by RawandDev** [comment]
I also love plain css and tailwind but I guess when you choose a library you need to stick with it xD
PS: remove the console log in `index.js` please.

**Comment by AramRafeq** [comment]
@RawandDev  could you migrate the vanilla css to use proper ant design grids and layout?

**Comment by RawandDev** [comment]
Sure, I will try in a few hours or tonight when I have electricity.

**Comment by AramRafeq** [comment]
#12

**Comment by rojvv** [comment]
#12 was merged.

**Comment by hezhamen** [comment]
thank god, finally

**Comment by RawandDev** [comment]
The website is not responsive. The antd layout was removed 🤣
