### ISSUE TITLE
[feature] add pagination

### ISSUE THREAD

**Issue by RawandDev** [hezhamen/awesome-kurds#8]
what do you guys think of adding pagination?

**Comment by AramRafeq** [comment]
Right now there is no need because our data is directly parsed from the readme

**Comment by RawandDev** [comment]
Sounds good. I already made some progress if you like I can push it.

**Comment by hezhamen** [comment]
Send a pr so we can see the result. It will be deployed by Vercel.

**Comment by RawandDev** [comment]
Done #9
